name: Auto Deploy on Comment

on:
  push:
    branches:
      - prod-cp
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install npm dependencies
      run: npm install
      
    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Execute ng build
      run: ng build --configuration=prod-cp

    - name: Install AWS CLI
      run: |
        pip install --upgrade pip
        pip install awscli
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ap-southeast-1  # Ganti dengan wilayah yang Anda inginkan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-southeast-1

    - name: Deploy
      run: |
        aws s3 sync dist/fuse/ s3://evgatecp.energie.co.id --delete
        aws cloudfront create-invalidation --distribution-id EAHH0T1LWNM1L --paths "/*"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
